package com.cs4135.Backend;

import static org.junit.jupiter.api.Assertions.*;

import java.time.DayOfWeek;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import com.cs4135.Backend.dto.request.AvailabilityCreationRequestDTO;
import com.cs4135.Backend.dto.request.BookMeetingRequestDTO;
import com.cs4135.Backend.dto.response.ConversationResponseDTO;
import com.cs4135.Backend.dto.response.MeetingResponseDTO;
import com.cs4135.Backend.dto.response.MessageResponseDTO;
import com.cs4135.Backend.entity.Admin;
import com.cs4135.Backend.entity.Availability;
import com.cs4135.Backend.entity.Conversation;
import com.cs4135.Backend.entity.Message;
import com.cs4135.Backend.entity.Staff;
import com.cs4135.Backend.entity.Student;
import com.cs4135.Backend.entity.TimeSlot;
import com.cs4135.Backend.repository.AdminRepository;
import com.cs4135.Backend.repository.AvailabilityRepository;
import com.cs4135.Backend.repository.ConversationRepository;
import com.cs4135.Backend.repository.MeetingRepository;
import com.cs4135.Backend.repository.MessageRepository;
import com.cs4135.Backend.repository.StaffRepository;
import com.cs4135.Backend.repository.StudentRepository;
import com.cs4135.Backend.repository.TimeSlotRepository;
import com.cs4135.Backend.repository.UserRepository;
import com.cs4135.Backend.serviceimpl.AvailabilityServiceImpl;
import com.cs4135.Backend.serviceimpl.ConversationServiceImpl;
import com.cs4135.Backend.serviceimpl.MeetingServiceImpl;

import jakarta.transaction.Transactional;

@SpringBootTest(properties = {
    "spring.datasource.url=jdbc:postgresql://localhost:5432/mydb",
    "spring.datasource.username=myuser",
    "spring.datasource.password=mypassword",
    "spring.jpa.hibernate.ddl-auto=update",
    "spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect"
})
public class UserRepositoryTests {
    @Autowired
    MeetingServiceImpl meetingServiceImpl;

    @Autowired
    ConversationServiceImpl conversationServiceImpl;

    @Autowired
    private AvailabilityServiceImpl availabilityServiceImpl;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private StaffRepository staffRepository;

    @Autowired
    private StudentRepository studentRepository;

    @Autowired 
    private AdminRepository adminRepository;

    @Autowired 
    AvailabilityRepository availabilityRepository;

    @Autowired
    TimeSlotRepository timeSlotRepository;

    @Autowired
    ConversationRepository conversationRepository;

    @Autowired
    MessageRepository messageRepository;

    @Autowired 
    MeetingRepository meetingRepository;

    @Transactional
    @Test
    public void testAddAndDeleteUser() {
        
        Staff staff = new Staff();
        staff.setName("Delete Me");
        staff.setEmail("delete@test.com");
        staff.setHashedPassword("dummy_pass"); // Make sure this isn't null if DB requires it

        
        Staff savedStaff = userRepository.save(staff);
        assertNotNull(savedStaff.getId(), "ID should be generated by Postgres");
        long count = userRepository.count();
        assertEquals(1, count);
        userRepository.delete(savedStaff);

        
        count = userRepository.count();
        assertEquals(0, count, "Database should be empty after deletion.");
        
        boolean exists = userRepository.findById(savedStaff.getId()).isPresent();
        assertFalse(exists, "User should no longer exist.");
    }

    @Transactional
    @Test
    public void testAddStaffStudentAdmin_PolymorphicRelationship() {
        Staff staff = new Staff();
        staff.setName("Delete Me Staff");
        staff.setEmail("delete@test.com");
        staff.setHashedPassword("dummy_pass");

        Student student = new Student();
        student.setName("Delete Me Student");
        student.setEmail("delete@test.com123");
        student.setHashedPassword("dummy_pass");

        Admin admin = new Admin();
        admin.setName("Delete Me");
        admin.setEmail("delete@test.com1234");
        admin.setHashedPassword("dummy_pass");

        staffRepository.save(staff);
        assertEquals(1, staffRepository.count());

        studentRepository.save(student);
        assertEquals(1, studentRepository.count());
        
        adminRepository.save(admin);
        assertEquals(1, adminRepository.count());
        
        assertEquals(3, userRepository.count());


        staffRepository.delete(staff);
        assertEquals(0, staffRepository.count());

        studentRepository.delete(student);
        assertEquals(0, studentRepository.count());

        adminRepository.delete(admin);
        assertEquals(0, adminRepository.count());

        assertEquals(0, userRepository.count());
    }
        @Transactional
        @Test
        public void testAvailabilityAdding_AlsoAddingTimeslots() {

            timeSlotRepository.deleteAll();
            availabilityRepository.deleteAll();
            staffRepository.deleteAll();
            
            Staff staff = new Staff();
            staff.setName("Delete Me Staff");
            staff.setEmail("delete@test.com56565");
            staff.setHashedPassword("dummy_pass");


            staffRepository.save(staff);
            Availability availability = new Availability();
            availability.setDay(DayOfWeek.WEDNESDAY);
            availability.setEndDate(LocalDate.of(2026, 4, 17));
            availability.setStartTime(LocalTime.of(12,0));
            availability.setEndTime(LocalTime.of(13, 0));
            availability.setStaff(staff);
            
            List<AvailabilityCreationRequestDTO> dtos = new ArrayList<>();
            AvailabilityCreationRequestDTO dto = new AvailabilityCreationRequestDTO();
            dto.setDay(DayOfWeek.WEDNESDAY);
            dto.setStartTime(LocalTime.of(12, 0));
            dto.setEndTime(LocalTime.of(13,0));
            dto.setEndDate(LocalDate.of(2026, 4, 30));
            dto.setTimeSlotLength(Duration.of(30,ChronoUnit.MINUTES));
            dto.setStaffId(staff.getId());
            dtos.add(dto);
            availabilityServiceImpl.generateSingleAvailability(dtos,LocalDate.of(2026, 4, 15));

            assertEquals(3, availabilityRepository.count());
            assertEquals(6, timeSlotRepository.count());

        }

        @Test
        public void testMessageGeneration() {
            messageRepository.deleteAll();
            conversationRepository.deleteAll();
            staffRepository.deleteAll();
            studentRepository.deleteAll();
            
            
            Staff staff = new Staff();
            staff.setName("Delete Me Staff");
            staff.setEmail("delete@test.com");
            staff.setHashedPassword("dummy_pass");
            staffRepository.save(staff);

            Student student = new Student();
            student.setName("Delete Me Student");
            student.setEmail("delete@test.com123");
            student.setHashedPassword("dummy_pass");
            studentRepository.save(student);

            ConversationResponseDTO dto = conversationServiceImpl.createOrGetConversation(student.getId(), staff.getEmail());
            assertEquals(1, conversationRepository.count());

            MessageResponseDTO messageDTO = conversationServiceImpl.sendMessage(dto.getId(), "Is the meeting still on", student.getEmail());
            Message message = messageRepository.findById(messageDTO.getId()).orElseThrow(() -> new AssertionError("Message not found"));
            String content = message.getContent();
            assertEquals("Is the meeting still on", content);

            messageRepository.deleteAll();
            conversationRepository.deleteAll();
            staffRepository.deleteAll();
            studentRepository.deleteAll();
        }



}