
# build and start all services
#   docker compose up --build

# build only the images
#   docker compose build

# start all services
#   docker compose up

# stop all services
#   docker compose down

# add --profile dev to also affect pgAdmin4 container
# (see below)

# Volumes are files that would not regularly be included in the image
# But are needed for the app to run

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - postgres
    networks:
      - backend-network
  
  frontend:
    build:
      context: ../GetInTouch-Frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
